import { BrandConfig } from '@/types';

const basePath = process.env.NEXT_PUBLIC_BASE_PATH || '';

export const brandConfig: BrandConfig = {
  name: 'Sforzato Music',
  motto: 'Impulsando música con propósito.',
  projectTitle: 'EN TU MEMORIA',
  projectTagline: 'El álbum que abraza la fe, la historia y la esperanza.',
  logoAsset: {
    path: `${basePath}/assets/brand/sforzato-music-logo-512.webp`, // Asset web optimizado (11.57 KB - 95.76% reducción)
    originalMasterPath: `${basePath}/assets/brand/sforzato-music-logo.webp`, // Master original (272.91 KB)
    alt: 'Sforzato Music',
    width: 512,
    height: 512,
    status: 'CONFIRMADO',
  },
  heroProvisionalAsset: {
    path: `${basePath}/assets/brand/hero-image-provisional-ai.webp`, // Asset gráfico provisional de preproducción (28.36 KB)
    alt: 'Ambiente estético de estudio de grabación (Asset provisional de preproducción)',
    isProvisional: true,
    status: 'CONFIRMADO',
  },
  coverProvisionalAsset: {
    path: `${basePath}/assets/brand/en-tu-memoria-cover-provisional-ai.webp`, // Arte conceptual promocional provisional de portada (53.24 KB)
    alt: 'Arte conceptual promocional del álbum En Tu Memoria (Asset provisional de preproducción)',
    isProvisional: true,
    status: 'CONFIRMADO',
  },
  ogProvisionalAsset: {
    path: `${basePath}/assets/brand/og-image-provisional-ai.webp`, // Asset social preview provisional 1200x630 (50.20 KB)
    alt: 'Sforzato Music — En Tu Memoria (Social Preview Provisional)',
    width: 1200,
    height: 630,
    isProvisional: true,
    status: 'CONFIRMADO',
  },
  biblicalConcept: {
    reference: 'Lucas 22:19',
    verseText: 'Hagan esto en memoria de mí',
    status: 'CONFIRMADO',
  },
  homage: {
    personName: 'Nicolás Lagos',
    departureDate: '01 de octubre de 2024',
    role: 'Cofundador de Sforzato Music',
    status: 'CONFIRMADO',
  },
  studioAssets: {
    primary: {
      path: `${basePath}/assets/studio/session-drums-live.webp`,
      alt: 'Sesión de grabación acústica de batería en vivo con microfonía multicanal en estudio durante la producción de En Tu Memoria',
      width: 1440,
      height: 810,
      caption: 'Sesión de captura acústica en vivo · Batería y percusiones en sala',
      tag: 'SESIÓN EN VIVO · LIVE ROOM',
      role: 'primary',
      status: 'CONFIRMADO',
    },
    secondaryConsole: {
      path: `${basePath}/assets/studio/session-console-mixing.webp`,
      alt: 'Ingeniero de sonido en consola analógica y estación digital Pro Tools en estudio durante la producción de En Tu Memoria',
      width: 1080,
      height: 608,
      caption: 'Ingeniería de sonido, mezcla y edición multipista',
      tag: 'CONTROL ROOM & CONSOLA',
      role: 'secondary',
      status: 'CONFIRMADO',
    },
    secondaryGuitar: {
      path: `${basePath}/assets/studio/session-guitar-detail.webp`,
      alt: 'Músico ejecutando digitación de acordes en mástil de guitarra acústica con clavijero dorado en sesión de estudio de En Tu Memoria',
      width: 1080,
      height: 608,
      caption: 'Arreglos acústicos y ejecución instrumental',
      tag: 'ARREGLOS & DETALLE',
      role: 'secondary',
      status: 'CONFIRMADO',
    },
    allCaptures: [
      {
        id: 'drums-live',
        path: `${basePath}/assets/studio/session-drums-live.webp`,
        alt: 'Sesión de grabación acústica de batería en vivo con microfonía multicanal en estudio durante la producción de En Tu Memoria',
        width: 1440,
        height: 810,
        tag: 'SESIÓN EN VIVO · LIVE ROOM',
        title: 'Captura acústica de percusiones en sala',
        caption: 'Batería acústica Pearl con microfonía multicanal completa en toma viva.',
        role: 'primary',
        status: 'CONFIRMADO',
      },
      {
        id: 'console-mixing',
        path: `${basePath}/assets/studio/session-console-mixing.webp`,
        alt: 'Ingeniero de sonido en consola analógica y estación digital Pro Tools en estudio durante la producción de En Tu Memoria',
        width: 1080,
        height: 608,
        tag: 'CONTROL ROOM & CONSOLA',
        title: 'Ingeniería de sonido y edición multipista',
        caption: 'Consola de mezcla analógica, monitores Genelec y sesión digital Pro Tools.',
        role: 'secondary',
        status: 'CONFIRMADO',
      },
      {
        id: 'guitar-detail',
        path: `${basePath}/assets/studio/session-guitar-detail.webp`,
        alt: 'Músico ejecutando digitación de acordes en mástil de guitarra acústica con clavijero dorado en sesión de estudio de En Tu Memoria',
        width: 1080,
        height: 608,
        tag: 'ARREGLOS & DETALLE',
        title: 'Arreglos acústicos y ejecución instrumental',
        caption: 'Detalle de digitación en mástil y clavijero dorado de guitarra de concierto.',
        role: 'secondary',
        status: 'CONFIRMADO',
      },
      {
        id: 'guitar-player',
        path: `${basePath}/assets/studio/session-guitar-player.webp`,
        alt: 'Músico guitarrista interpretando en sala de grabación en estudio durante la producción de En Tu Memoria',
        width: 1440,
        height: 810,
        tag: 'INTERPRETACIÓN · TOMA ACÚSTICA',
        title: 'Sesión instrumental de guitarra',
        caption: 'Interpretación solista y armonías en sala acondicionada acústicamente.',
        role: 'documentary',
        status: 'CONFIRMADO',
      },
      {
        id: 'control-room-team',
        path: `${basePath}/assets/studio/session-control-room-team.webp`,
        alt: 'Productor e ingeniero de sonido evaluando pistas de grabación frente a monitores de estudio en En Tu Memoria',
        width: 1440,
        height: 810,
        tag: 'DIRECCIÓN & ESCUCHA CRÍTICA',
        title: 'Supervisión y control de tomas',
        caption: 'Evaluación crítica de dinámicas y balance sonoro en sala de control.',
        role: 'documentary',
        status: 'CONFIRMADO',
      },
      {
        id: 'control-room-wide',
        path: `${basePath}/assets/studio/session-control-room-wide.webp`,
        alt: 'Equipo de producción en sala de control frente a la consola de grabación en En Tu Memoria',
        width: 1440,
        height: 810,
        tag: 'SALA DE CONTROL · PANORÁMICA',
        title: 'Perspectiva del equipo de producción',
        caption: 'Monitoreo de estudio y seguimiento integral de la jornada de grabación.',
        role: 'documentary',
        status: 'CONFIRMADO',
      },
      {
        id: 'team-atmosphere',
        path: `${basePath}/assets/studio/session-team-atmosphere.webp`,
        alt: 'Equipo creativo y músicos en sesión de estudio durante la producción de Sforzato Music',
        width: 1440,
        height: 810,
        tag: 'EQUIPO CREATIVO · DIÁLOGO',
        title: 'Comunión y proceso creativo',
        caption: 'Intercambio de visiones y arreglos entre el equipo de producción y músicos.',
        role: 'documentary',
        status: 'CONFIRMADO',
      },
      {
        id: 'console-faders',
        path: `${basePath}/assets/studio/session-console-faders.webp`,
        alt: 'Superficie de consola analógica con faders y cintas de rotulación de pistas en estudio',
        width: 1440,
        height: 810,
        tag: 'HARDWARE ANALÓGICO · TRACKING',
        title: 'Faders y ruteo analógico',
        caption: 'Calibración de canales, preamplificación y marcado de tomas instrumentales.',
        role: 'documentary',
        status: 'CONFIRMADO',
      },
      {
        id: 'studio-door',
        path: `${basePath}/assets/studio/session-studio-door.webp`,
        alt: 'Placa identificatoria de Estudio A en sala de grabación de Sforzato Music',
        width: 1440,
        height: 810,
        tag: 'INSTALACIONES · ESPACIO DE TRABAJO',
        title: 'Estudio A — Sala de Grabación',
        caption: 'Ingreso a la cabina principal donde se registraron las sesiones del proyecto.',
        role: 'documentary',
        status: 'CONFIRMADO',
      },
      {
        id: 'hallway-access',
        path: `${basePath}/assets/studio/session-hallway-access.webp`,
        alt: 'Registro documental en pasillo de acceso a salas de grabación de Sforzato Music',
        width: 1440,
        height: 810,
        tag: 'ENTORNO DOCUMENTAL · BACKSTAGE',
        title: 'Pasillos y accesos a cabinas',
        caption: 'Registro documental del entorno y dinámica de trabajo entre tomas de grabación.',
        role: 'documentary',
        status: 'CONFIRMADO',
      },
    ],
  },
};
